STATIC_FOLDER = 'static'
TEMPLATE_FOLDER = 'templates'
SECRET_KEY = 'yg87uhf9ub2987yh9ubUdvb9283d23df2938uf02ojnd239dy239ubd9'
VALID_ROOMS = (
	"Physics",
	"Chemistry",
	"Biology",
	"Math",
	"English",
	"History",
	"Geography",
	"Computer Science",
	"Art",
	"Music",
	"Literature",
	"Philosophy",
	"Economics",
	"Business",
	"Political Science",
	"Psychology",
	"Sociology",
	"Law",
	"Medicine",
	"Nursing",
	"Education",
	"Architecture",
	"Engineering",
	"Agriculture",
	"Veterinary Medicine",
	"Pharmacy",
	"Dentistry",
	"Optometry",
	"Surgery",
	"Veterinary Science",
	"Veterinary Technology",
	"Veterinary Medicine",
	"Veterinary Dentistry",
	"Veterinary Surgery",
	"Veterinary Pharmacy",
	"Veterinary Optometry",
	"Science",
)